[package]
name = "characterai-client-linux"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
glib = "0.19"
gtk = { package = "gtk4", version = "0.8", features = ["v4_8"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
